project:
  type: book

book:
  title: "Manual de introducción a R"
  author: "Creado por: Dr. Leonel Lerebours y Dr. Yunior Rosario </br> Editado por: Virginia Vallejo"
  date: "7/29/2025"
  
  chapters:
    - index.qmd
    - 01-instalacionR.qmd
    - 02-comanzandousandoR.qmd
    - 03-operadoresR.qmd
    - 04-objetosenr.qmd
    - 05-excel_a_R_intro.qmd
    - 06-analisisresultados.qmd
    - 07-reporte.qmd
    - 08-analisisEstadistico.qmd
    - references.qmd

    
language: langu.yml

bibliography: references.bib

format:
  html:
    theme:
      - journal
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

